sensors:
  lidar_port: "/dev/ttyUSB0"
  camera_resolution: [640, 480]
  use_mock: true

ai:
  snn:
    neurons: 128
    learning_rate: 0.01
    simulation_mode: true

swarm:
  node_count: 5
  communication: "MQTT"

actuators:
  motor_max_speed: 100
