name: CI - Brain Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ffmpeg libglib2.0-0

      - name: Create virtualenv and install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          if [ -f "./requirements.txt" ]; then pip install -r ./requirements.txt; fi
          # CPU PyTorch (safe default). For GPU runners change this.
          pip install --no-deps torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu || true
          pip install -e .

      - name: Lint (flake8)
        run: |
          . .venv/bin/activate
          pip install flake8 || true
          flake8 || true

      - name: Run simulate.py (if present)
        run: |
          . .venv/bin/activate
          if [ -f "simulate.py" ]; then python simulate.py || true; fi

      - name: Run tests (if any)
        run: |
          . .venv/bin/activate
          if [ -d "tests" ]; then pip install pytest || true; pytest -q || true; fi

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t web4application/brain:latest .
