name: CI - Build & Test Brain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ / ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ffmpeg libglib2.0-0

      - name: Create venv & install requirements
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          if [ -f "./requirements.txt" ]; then pip install -r ./requirements.txt; fi
          pip install --no-deps torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu || true
          pip install -e .

      - name: Lint (optional)
        run: |
          . .venv/bin/activate
          pip install flake8 || true
          flake8 || true

      - name: Run simulate.py (if present)
        run: |
          . .venv/bin/activate
          if [ -f "simulate.py" ]; then python simulate.py || true; fi

      - name: Run tests (if any)
        run: |
          . .venv/bin/activate
          if [ -d "tests" ]; then pytest -q || true; fi

  build-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t web4application/brainneuron.ai:latest .
